### ISSUE TITLE
Not working with docker for windows 

### ISSUE THREAD

**Issue by luissalgadofreire** [LDSSA/setup#3]
I have tried to install following the instructions but the notebook opens with no files inside so the volume mount doesn't seem to work with the given `docker run command` for some reason.

I have the following version of docker for windows (the native one, not the toolbox): `Docker version 17.06.0-ce, build 02c1d87`.

I got it to work using the following equivalent `docker-compose` file though:

```
version: '3.1'

services:

  jupyter:
    restart: always
    image: ldssa/learning-units:latest
    ports:
      - "8888:8888"
    working_dir: /root/units
    volumes:
      - .:/root/units
```

which I run with:
```
docker-compose up -d
```

I don't know why the plain docker command is not mapping the current folder into the container's folder but it's working with this alternative. My concern is just so that others might have a workaround in case their work environment has the same behavior as mine.
